spring:
  application:
    name: manjok

  config:
    import: optional:file:.env[.properties]

  output:
    ansi:
      enabled: always

  profiles:
#    active: develop
    active: main

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${EMAIL_PW}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        debug: true

logging:
  level:
    root: info
    xyz.sparta-project: debug

jwt:
  secret: ${JWT_ENC_KEY}
  token-exp: 1800000  # 30ë¶„

backend:
  base-url: ${BASE_URL:http://localhost:8080}


springdoc:
  version: '1.0.0'
  default-consumes-media-type: application/json
  default-produces-media-type: application/json