spring:
  application:
    name: manjok
  profiles:
    active: develop
#    active: main

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: info
    xyz.sparta-project: debug